name: "Update and Inclusion of the Official Gentoo Overlay"

on:
  schedule:
    - cron: '0 0 * * *'
  
  workflow_dispatch: # Permite que executes manualmente na aba Actions para testar agora

permissions:
  contents: write

jobs:
  execucao-rotina:
    name: "Executar Comandos em Sequência"
    runs-on: ubuntu-latest # Usa a versão estável mais atual do Ubuntu

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4


      - name: Configurar Python 3.14.6
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.6'
      - name: "Running the Python code."
        shell: python
        run: |
          import 

      - name: "Publicar resultados no repositório"
        run: |
          echo "=== CONFIGURANDO GIT ==="
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          echo "=== ANEXANDO FICHEIROS ==="
          git add .

          echo "=== FAZENDO COMMIT ==="
          git commit -m "Atualização automática da rotina diária [skip ci]" || echo "Nenhuma alteração para publicar."
          
          echo "=== FAZENDO REBASE ==="
          # O --rebase puxa as alterações dos outros e mete o teu commit no topo
          git pull --rebase origin main

          echo "=== SUBMITTING THE CHANGES ==="
          git push